Fixed v-model and added 'inputEmited' feature
tjs-libs/vue-formats pull request #20
Opened 2021-03-04 17:54 UTC by VoIdJMp

2021-03-04 19:02 UTC, fayzzzm commented
@VoIdJMp names of commits and PR should be capitalized and should be at least meaningful.

2021-03-04 19:05 UTC, fayzzzm requested changes

2021-03-04 19:05 UTC, fayzzzm commented on .codesandbox/ci.json
> +  "sandboxes": ["new", "vanilla"]
This is fixed, first, you should merge the first PR and pull it there, and should be OK.

2021-03-04 19:05 UTC, fayzzzm commented on src/components/VueMoney.js
> +        min_max: {
`min_max, oldValue` are two separate methodologies of naming. Either do `minMax` or `old-value`

2021-03-04 19:05 UTC, fayzzzm commented on src/components/VueMoney.js
> +    },
nice

2021-03-04 19:05 UTC, fayzzzm commented on src/components/VueMoney.js
> +        onInput(e) {
use event better

2021-03-04 19:05 UTC, fayzzzm commented on src/components/VueMoney.js
> +    render(h) {
same for here, dont' use `h` use something else

2021-03-05 02:40 UTC, VoIdJMp commented on src/components/VueMoney.js
> +        onInput(e) {
Ok

2021-03-06 14:54 UTC, VoIdJMp commented on src/app.js
> +        value: { required: true, type: [Number, String], default: 0 },
I suggest using this style of writing props (inline). 
I think it will be convenient.

2021-03-06 16:14 UTC, merged